#!/bin/bash
# Analyzes system_monitor.log generated by monitor.sh.

set -u

LOG_FILE="${1:-system_monitor.log}"

if [[ ! -f "$LOG_FILE" ]]; then
    echo "ERROR: Log file not found: $LOG_FILE" >&2
    exit 1
fi

echo "============================================================"
echo "System Resource Monitoring Analysis"
echo "============================================================"

echo
echo "Top CPU-consuming process observations:"
echo "------------------------------------------------------------"

awk '
/^[0-9]+[[:space:]]+/ {
    pid=$1
    user=$2
    cpu=$3
    mem=$4
    stat=$5
    command=""
    for (i=6; i<=NF; i++) command = command (i==6 ? "" : " ") $i

    gsub(/%/, "", cpu)
    gsub(/%/, "", mem)

    if (cpu ~ /^[0-9]+([.][0-9]+)?$/) {
        printf "%8s %-12s %8.1f%% %8.1f%% %s\n", pid, user, cpu, mem, command
    }
}' "$LOG_FILE" | sort -k3,3nr | head -n 10

echo
echo "Peak CPU observation:"
awk '
/^[0-9]+[[:space:]]+/ {
    cpu=$3
    gsub(/%/, "", cpu)
    if (cpu ~ /^[0-9]+([.][0-9]+)?$/) {
        if (cpu+0 > max) {
            max=cpu+0
            pid=$1
            command=""
            for (i=6; i<=NF; i++) command = command (i==6 ? "" : " ") $i
        }
    }
}
END {
    if (max >= 0)
        printf "PID=%s CPU=%.1f%% COMMAND=%s\n", pid, max, command
}' "$LOG_FILE"

echo
echo "Analysis complete."
